CARRIER_MAP = {
    "com-elec": "Commercial Electrical",
    "com-total-air-con": "Commercial Air Conditioner",
    "com-total-cool": "Commercial Cooling",
    "com-total-cool-dr": "Commercial Cooling Demand Response",
    "com-total-elec": "Commercial Electrical",
    "com-total-elec-dr": "Commercial Electrical Demand Response",
    "com-total-space-elec-furnace": "Commercial Electric Furnace",
    "com-total-space-gas-furnace": "Commercial Gas Furnace",
    "com-total-space-heat": "Commercial Heating",
    "com-total-space-heat-dr": "Commercial Heating Demand Response",
    "com-total-space-oil-furnace": "Commercial Oil Furnace",
    "com-total-water-elec": "Commercial Electric Water Heater",
    "com-total-water-gas": "Commercial Gas Water Heater",
    "com-total-water-oil": "Commercial Oil Water Heater",
    "com-total-ashp": "Commercial Heat Pump",
    "com-total-gshp": "Commercial Heat Pump",
    "ind-coal-furnace": "Industrial Coal Furnace",
    "ind-elec": "Industrial Electric",
    "ind-elec-dr": "Industrial Electric Demand Response",
    "ind-gas-furnace": "Industrial Gas Furnace",
    "ind-heat": "Industrial Heating",
    "ind-heat-dr": "Industrial Heating Demand Response",
    "ind-heat-pump": "Industrial Heat Pump",
    "res-elec": "Residential Electrical",
    "res-total-air-con": "Residential Air Conditioner",
    "res-total-cool": "Residential Cooling",
    "res-total-cool-dr": "Residential Cooling Demand Response",
    "res-total-elec": "Residential Electrical",
    "res-total-elec-dr": "Residential Electrical Demand Response",
    "res-total-space-elec-furnace": "Residential Electrical Furnace",
    "res-total-space-gas-furnace": "Residential Gas Furnace",
    "res-total-space-heat": "Residential Heating",
    "res-total-space-heat-dr": "Residential Heating Demand Response",
    "res-total-space-oil-furnace": "Residential Oil Furnace",
    "res-total-water-elec": "Residential Electric Water Heater",
    "res-total-water-gas": "Residential Gas Water Heater",
    "res-total-water-oil": "Residential Oil Water Heater",
    "res-total-ashp": "Residential Heat Pump",
    "res-total-gshp": "Residential Heat Pump",
    "trn-elec-veh": "Transport Electric Vehicle",
    "trn-elec-veh-dr": "Transport Demand Response",
    "trn-elec-veh-bus": "Transport Electric Bus",
    "trn-elec-veh-hvy": "Transport Electric Heavy",
    "trn-elec-veh-lgt": "Transport Electric Light",
    "trn-elec-veh-med": "Transport Electric Medium",
    "trn-lpg-air": "Transport Lpg Non-Vehicle",
    "trn-lpg-air-psg": "Transport Lpg Non-Vehicle",
    "trn-lpg-boat": "Transport Lpg Non-Vehicle",
    "trn-lpg-boat-ship": "Transport Lpg Non-Vehicle",
    "trn-lpg-rail": "Transport Lpg Non-Vehicle",
    "trn-lpg-rail-psg": "Transport Lpg Non-Vehicle",
    "trn-lpg-rail-ship": "Transport Lpg Non-Vehicle",
    "trn-lpg-veh": "Transport Lpg Vehicle",
    "trn-lpg-veh-bus": "Transport Lpg Bus",
    "trn-lpg-veh-hvy": "Transport Lpg Heavy",
    "trn-lpg-veh-lgt": "Transport Lpg Light",
    "trn-lpg-veh-med": "Transport Lpg Medium",
    "AC": "Electrical Network",
    "biomass": "Biomass",
    "CCGT": "Natural Gas CCGT",
    "CCGT-95CCS": "Natural Gas CCGT-95CCS",
    "coal": "Coal",
    "geothermal": "Geothermal",
    "hydro": "Hydro",
    "nuclear": "Nuclear",
    "offwind_floating": "Wind",
    "OCGT": "Natural Gas OCGT",
    "onwind": "Wind",
    "solar": "Solar",
    "waste": "Waste",
    "4hr_battery_storage": "Battery",
    "8hr_battery_storage": "Battery",
    "battery": "Battery",
    "ch4": "Methane",
    "co2": "Carbon Dioxide",
    "gas pipeline": "Gas Network",
    "gas production": "Gas Network",
    "gas storage": "Gas Network",
    "gas trade": "Gas Network",
    "oil": "Oil",
    "imports": "Imports",
    "exports": "Exports",
}
